// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Conversation struct {
	ID             int64
	TelegramUserID int64
	Messages       json.RawMessage
	Created        time.Time
	Updated        time.Time
}

type UserCredit struct {
	ID             int64
	UserID         int64
	CreditsBalance int32
	Created        time.Time
	Updated        time.Time
}

type UserInfo struct {
	UserID            int64
	TelegramUserID    int64
	TelegramUsername  sql.NullString
	TelegramFirstName sql.NullString
	TelegramLastName  sql.NullString
	Created           time.Time
}
