// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"database/sql"
	"time"
)

type SubscriptionPlan struct {
	ID                   int64
	UserID               int64
	StripeSubscriptionID sql.NullString
	ResourcesIncluded    int32
	ResourcesUsed        int32
	Created              time.Time
}

type UserInfo struct {
	UserID             int64
	Email              string
	FullName           string
	OnboardingComplete bool
	Created            time.Time
}
