// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Conversation struct {
	ID             int64
	TelegramUserID int64
	Messages       json.RawMessage
	Created        time.Time
	Updated        time.Time
}

type SubscriptionPlan struct {
	ID                   int64
	UserID               int64
	StripeSubscriptionID sql.NullString
	ResourcesIncluded    int32
	ResourcesUsed        int32
	Created              time.Time
}

type UserInfo struct {
	UserID            int64
	TelegramUserID    int64
	TelegramUsername  sql.NullString
	TelegramFirstName sql.NullString
	TelegramLastName  sql.NullString
	Created           time.Time
}
